package org.ams.db;

// Generated Oct 23, 2012 12:11:32 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Module generated by hbm2java
 */
public class Module implements java.io.Serializable ,BusinessEntity{

	private Integer mid;
	private String name;
	private String code;
	private int level;
	private Set<Record> records = new HashSet<Record>(0);
	private Set<User> users = new HashSet<User>(0);
	private Set<Student> students = new HashSet<Student>(0);
	private Set<Program> programs = new HashSet<Program>(0);

	public Module() {
	}

	public Module(String name, String code, int level) {
		this.name = name;
		this.code = code;
		this.level = level;
	}

	public Module(String name, String code, int level, Set<Record> records,
			Set<User> users, Set<Student> students, Set<Program> programs) {
		this.name = name;
		this.code = code;
		this.level = level;
		this.records = records;
		this.users = users;
		this.students = students;
		this.programs = programs;
	}

	public Integer getMid() {
		return this.mid;
	}

	public void setMid(Integer mid) {
		this.mid = mid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public int getLevel() {
		return this.level;
	}

	public void setLevel(int level) {
		this.level = level;
	}

	public Set<Record> getRecords() {
		return this.records;
	}

	public void setRecords(Set<Record> records) {
		this.records = records;
	}

	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	public Set<Student> getStudents() {
		return this.students;
	}

	public void setStudents(Set<Student> students) {
		this.students = students;
	}

	public Set<Program> getPrograms() {
		return this.programs;
	}

	public void setPrograms(Set<Program> programs) {
		this.programs = programs;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Module other = (Module) obj;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		if (code == null) {
			if (other.code != null)
				return false;
		} else if (!code.equals(other.code))
			return false;
		if (mid == null) {
			if (other.mid != null)
				return false;
		} else if (!mid.equals(other.mid))
			return false;
		return true;
	}

	@Override
	public String toString() {
		String s = this.name;
		return s;
	}
	
}
