package org.ams.db;

// Generated Oct 23, 2012 12:11:32 PM by Hibernate Tools 3.4.0.CR1






import java.util.HashSet;
import java.util.Set;

/**
 * Program generated by hbm2java
 */
public class Program implements java.io.Serializable,BusinessEntity {

	private Integer pid;
	private String name;
	private Set<Module> modules = new HashSet<Module>(0);
	private Set<Student> students = new HashSet<Student>(0);
	private Set<User> users = new HashSet<User>(0);

	public Program() {
	}

	public Program(String name) {
		this.name = name;
	}

	public Program(String name, Set<Module> modules) {
		this.name = name;
		this.modules = modules;
	}

	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Module> getModules() {
		return this.modules;
	}

	public void setModules(Set<Module> modules) {
		this.modules = modules;
	}
	public Set<Student> getStudents() {
		return this.students;
	}

	public void setStudents(Set<Student> students) {
		this.students = students;
	}
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}



	@Override
	public String toString() {
		String s = this.name;
		return s;
	}
	
}
