package org.ams.db;

// Generated Oct 23, 2012 12:11:32 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Record generated by hbm2java
 */
public class Record implements java.io.Serializable,BusinessEntity {

	private Integer rid;
	private Student student;
	private Module module;
	private Date date;
	private boolean attend;

	public Record() {
	}

	public Record(Student student, Module module, Date date, boolean attend) {
		this.student = student;
		this.module = module;
		this.date = date;
		this.attend = attend;
	}

	public Integer getRid() {
		return this.rid;
	}

	public void setRid(Integer rid) {
		this.rid = rid;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	public Module getModule() {
		return this.module;
	}

	public void setModule(Module module) {
		this.module = module;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public boolean isAttend() {
		return this.attend;
	}
	

	public void setAttend(boolean attend) {
		this.attend = attend;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + (attend ? 1231 : 1237);
		result = prime * result + ((date == null) ? 0 : date.hashCode());
		result = prime * result + ((module == null) ? 0 : module.hashCode());
		result = prime * result + ((rid == null) ? 0 : rid.hashCode());
		result = prime * result + ((student == null) ? 0 : student.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Record other = (Record) obj;
		if (attend != other.attend)
			return false;
		if (date == null) {
			if (other.date != null)
				return false;
		} else if (!date.equals(other.date))
			return false;
		if (module == null) {
			if (other.module != null)
				return false;
		} else if (!module.equals(other.module))
			return false;
		if (rid == null) {
			if (other.rid != null)
				return false;
		} else if (!rid.equals(other.rid))
			return false;
		if (student == null) {
			if (other.student != null)
				return false;
		} else if (!student.equals(other.student))
			return false;
		return true;
	}

	private String pringAttendance(){
		String s;
		if(isAttend()){
			s = "Present";
		}
		else{
			s = "Absent";
		}
		return s;
	}
	
	@Override
	public String toString() {
		String s = student.getName()+" - "+module.getName() + " - " + date + " - " + pringAttendance();
		return s;
	}
	
	

}
