package org.ams.db;

// Generated Oct 23, 2012 12:11:32 PM by Hibernate Tools 3.4.0.CR1





import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable,BusinessEntity {

	private Integer sid;
	private String name;
	private String rn;
	private Program program;
	private String email;
	private Set<Record> records = new HashSet<Record>(0);
	private Set<Module> modules = new HashSet<Module>(0);

	public Student() {
	}

	public Student(String name, String rn,String email) {
		this.name = name;
		this.rn = rn;
		this.email = email;
	}

	public Student(String name, String rn, Set<Record> records,
			Set<Module> modules) {
		this.name = name;
		this.rn = rn;
		this.records = records;
		this.modules = modules;
	}

	public Integer getSid() {
		return this.sid;
	}

	public void setSid(Integer sid) {
		this.sid = sid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getRn() {
		return this.rn;
	}

	public void setRn(String rn) {
		this.rn = rn;
	}

	public Set<Record> getRecords() {
		return this.records;
	}

	public void setRecords(Set<Record> records) {
		this.records = records;
	}

	public Set<Module> getModules() {
		return this.modules;
	}

	public void setModules(Set<Module> modules) {
		this.modules = modules;
	}
	
	public Program getProgram() {
		return this.program;
	}

	public void setProgram(Program program) {
		this.program = program;
	}


    public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Student other = (Student) obj;
        if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;

		if (rn == null) {
			if (other.rn != null)
				return false;
		} else if (!rn.equals(other.rn))
			return false;
		if (sid == null) {
			if (other.sid != null)
				return false;
		} else if (!sid.equals(other.sid))
			return false;
		return true;
	}

	@Override
	public String toString() {
		String s = this.name;
		return s;
	}
	
}
