package org.ams.db;

// Generated Oct 23, 2012 12:11:32 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable ,BusinessEntity{

	public static final int ADMINISTRATOR = 0;
	public static final int PROGRAM_LEADER = 1;
	public static final int LECTURER = 2;
	
	private int uid;
	private String name;
	private String pwd;
	private int perm;
	private Program program;
	private String aname;
	private Set<Module> modules = new HashSet<Module>(0);

	public User() {
	}

	public User(String aname, String name, String pwd, int perm) {
		this.aname = aname;
		this.name = name;
		this.pwd = pwd;
		this.perm = perm;
	}
	public User(int uid, String name, String pwd, int perm) {
		this.uid = uid;
		this.name = name;
		this.pwd = pwd;
		this.perm = perm;
	}

	public User(int uid, String name, String pwd, int perm, Set<Module> modules) {
		this.uid = uid;
		this.name = name;
		this.pwd = pwd;
		this.perm = perm;
		this.modules = modules;
	}
	
	

	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	public int getPerm() {
		return this.perm;
	}

	public void setPerm(int perm) {
		this.perm = perm;
	}

	public Program getProgram() {
		return program;
	}

	public void setProgram(Program program) {
		this.program = program;
	}

	public Set<Module> getModules() {
		return this.modules;
	}

	public void setModules(Set<Module> modules) {
		this.modules = modules;
	}
	

	public String getAname() {
		return aname;
	}

	public void setAname(String aname) {
		this.aname = aname;
	}
	
	

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		User other = (User) obj;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		return true;
	}

	@Override
	public String toString() {
		String s = this.name + " - "+this.aname;
		return s;
	}
}
